-- MySQL Script generated by MySQL Workbench
-- Sat Oct 20 02:01:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema service
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `service` DEFAULT CHARACTER SET utf8 ;
USE `service` ;

-- -----------------------------------------------------
-- Table `service`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`Person` (
  `personID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `personName` VARCHAR(45) NOT NULL,
  `personEmail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`personID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`City` (
  `cityID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cityName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service`.`Building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`Building` (
  `buildingID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `buildingName` VARCHAR(45) NOT NULL,
  `cityID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`buildingID`),
  INDEX `fk_Building_City1_idx` (`cityID` ASC) ,
  CONSTRAINT `fk_Building_City1`
    FOREIGN KEY (`cityID`)
    REFERENCES `service`.`City` (`cityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service`.`Section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`Section` (
  `sectionID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sectionName` VARCHAR(45) NOT NULL,
  `buildingID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sectionID`),
  INDEX `fk_Section_Building1_idx` (`buildingID` ASC) ,
  CONSTRAINT `fk_Section_Building1`
    FOREIGN KEY (`buildingID`)
    REFERENCES `service`.`Building` (`buildingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`Room` (
  `roomID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `roomName` VARCHAR(45) NOT NULL,
  `sectionID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`roomID`),
  INDEX `fk_Room_Section1_idx` (`sectionID` ASC) ,
  CONSTRAINT `fk_Room_Section1`
    FOREIGN KEY (`sectionID`)
    REFERENCES `service`.`Section` (`sectionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service`.`Beacon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`Beacon` (
  `thingID` VARCHAR(45) NOT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`thingID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service`.`MHub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`MHub` (
  `mhubID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`mhubID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service`.`Device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`Device` (
  `deviceID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `manufacturer` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `mhubID` VARCHAR(45) NOT NULL,
  `thingID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`deviceID`),
  INDEX `fk_Device_Mhub1_idx` (`mhubID` ASC) ,
  INDEX `fk_Device_Beacon1_idx` (`thingID` ASC) ,
  CONSTRAINT `fk_Device_Mhub1`
    FOREIGN KEY (`mhubID`)
    REFERENCES `service`.`MHub` (`mhubID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Device_Beacon1`
    FOREIGN KEY (`thingID`)
    REFERENCES `service`.`Beacon` (`thingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service`.`HasA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`HasA` (
  `belongsToID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `deviceID` INT UNSIGNED NOT NULL,
  `personID` INT UNSIGNED NOT NULL,
  `roomID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`belongsToID`),
  INDEX `fk_BelongsTo_Device1_idx` (`deviceID` ASC) ,
  INDEX `fk_BelongsTo_Person1_idx` (`personID` ASC) ,
  INDEX `fk_BelongsTo_Room1_idx` (`roomID` ASC) ,
  CONSTRAINT `fk_BelongsTo_Device1`
    FOREIGN KEY (`deviceID`)
    REFERENCES `service`.`Device` (`deviceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BelongsTo_Person1`
    FOREIGN KEY (`personID`)
    REFERENCES `service`.`Person` (`personID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BelongsTo_Room1`
    FOREIGN KEY (`roomID`)
    REFERENCES `service`.`Room` (`roomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
